name: cce_map
description: "Indoor Navigation Digital Twin - Phase 1"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # Maps - flutter_map ecosystem
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_geojson: ^1.0.5
  
  # State Management (hybrid: Provider + Riverpod)
  flutter_riverpod: ^2.4.9
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Networking & Caching
  http: ^1.2.0
  cached_network_image: ^3.3.1
  panorama_viewer: ^2.0.7
  
  # Utilities
  uuid: ^4.2.2
  collection: ^1.18.0
  fluttertoast: ^8.2.4
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # Local save server dependencies
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/maps/
    - assets/data/
    - assets/data/cce_test.geojson
