name: cce_map
description: "Indoor Navigation Digital Twin - Phase 1"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # Maps
  google_maps_flutter: ^2.5.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  uuid: ^4.2.2
  collection: ^1.18.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/maps/
    - assets/data/
